$border               = rgb(ffb68c)
$red                  = rgb(ffb4ab)
$surface1             = rgb(312823)
$base                 = rgb(1a120d)

$text_hex             = f0dfd7
$subtext_hex          = d7c2b8

$text                 = rgb($text_hex)
$subtext              = rgb($subtext_hex)
$overlay1             = rgb(9f8d84)
$overlay2             = rgb(52443c)

$blue_glow            = rgba(ffb68c)
