$border               = rgb(b0c6ff)
$red                  = rgb(ffb4ab)
$surface1             = rgb(282a2f)
$base                 = rgb(121318)

$text_hex             = e2e2e9
$subtext_hex          = c5c6d0

$text                 = rgb($text_hex)
$subtext              = rgb($subtext_hex)
$overlay1             = rgb(8f9099)
$overlay2             = rgb(44464f)

$blue_glow            = rgba(b0c6ff)
