#pragma once

// Auto-generated by cbindgen from the Rust extern "C" surface. Do not edit; edit the Rust and rebuild.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Opaque per-instance handle owned by the C++ `QsNativeBacklight` `QObject`.
struct BacklightHandle;

// Opaque per-instance handle owned by the C++ `QsNativeBluetooth` `QObject`.
//
// Holds the currently-running discovery monitor (if any). All access is from
// the Qt thread, but the worker join happens under the lock so `_Delete`
// during an in-flight monitor is safe.
struct BluetoothHandle;

// Opaque per-instance handle owned by the C++ `QsNativeConfigResolver` `QObject`.
struct ConfigResolverHandle;

// Opaque per-instance handle owned by the C++ `QsNativeIdle` `QObject`.
struct IdleHandle;

// Opaque per-instance handle owned by the C++ `QsNativeKeyboardLock` `QObject`.
struct KeyboardLockHandle;

// Opaque per-instance state owned by the C++ `QsNativeNetStats` `QObject`.
//
// Holds the cross-call traffic history/smoothing state plus the source-switch
// bookkeeping; the scalar properties (device, rx/tx counters, per-sec rates,
// error) are mirrored on the C++ side from the JSON snapshots returned here.
struct NetStatsHandle;

// Opaque per-instance handle owned by the C++ `QsNativePacman` `QObject`.
struct PacmanHandle;

// Opaque per-instance handle owned by the C++ `QsNativePrivacy` `QObject`.
//
// `alive` is shared with the persistent inotify watcher and every probe worker
// so they stop delivering callbacks once the `QObject` has been destroyed.
struct PrivacyHandle;

// Opaque per-instance handle owned by the C++ `QsNativeSysInfo` `QObject`.
struct SysInfoHandle;

// Opaque per-instance handle owned by the C++ `QsNativeSystemdFailedProvider`.
//
struct SystemdFailedHandle;

// Opaque per-instance handle owned by the C++ `QsNativeTodoist` `QObject`.
//
// The Todoist client keeps no cross-refresh state in Rust (the sync cache lives
// on disk, and `cache_path`/`prefer_cache` are QML-side inputs passed into each
// call), so the handle is empty. It exists only to mirror the New/Delete
// lifecycle of the other providers; the worker never dereferences it, so a
// `_Delete` racing an in-flight refresh is safe.
struct TodoistHandle;

using TokenCallback = void(*)(void*, const char*, int);

// Zero-copy scalar-state snapshot handed to the C++ side. The `*const c_char`
// fields borrow `CString`s that live on the worker/caller stack **only for the
// duration of the callback**; C++ must copy them (`QString::fromUtf8`)
// synchronously and must not retain the pointers. Fields map 1:1 to the
// `BacklightProvider` scalar QML properties.
struct BacklightSnapshotC {
  bool available;
  int32_t brightness_percent;
  const char *device;
  const char *error;
};

// Delivers a `BacklightSnapshotC` (borrowed for the call only) to the C++ side.
using BacklightSnapshotFn = void(*)(void*, const BacklightSnapshotC*);

// Callback used by threaded providers to deliver a JSON snapshot to C++.
//
// The `json` pointer is borrowed for the duration of the call only: the C++
// side must copy it (`QString::fromUtf8`) and must **not** free it.
using QsNativeUpdateFn = void(*)(void *ctx, const char *json);

// Zero-copy snapshot of the QML-facing properties. The `error` `*const c_char`
// borrows a `CString` that lives on the caller's stack **only for the duration
// of the callback**; C++ must copy it (`QString::fromUtf8`) synchronously and
// must not retain the pointer. Fields map 1:1 to `IdleProvider` QML properties.
struct IdleSnapshotC {
  int32_t display_off_timeout_sec;
  int32_t suspend_timeout_sec;
  bool suspend_enabled;
  bool ignore_lid_events;
  bool lid_inhibited;
  const char *error;
};

// Delivers an `IdleSnapshotC` (borrowed for the call only) to the C++ side.
using IdleSnapshotFn = void(*)(void*, const IdleSnapshotC*);

// Zero-copy event handed to the C++ side. The `*const c_char` fields borrow
// `CString`s that live on the worker stack **only for the duration of the
// callback**; C++ must copy them (`QString::fromUtf8`) synchronously and must
// not retain the pointers. `event_type` is one of `available`/`error`/`lock`;
// `message` carries the error text, `key` the `caps`/`num` toggle, and
// `enabled` its new state. Unused fields are empty/false for a given kind.
struct KeyboardLockSnapshotC {
  const char *event_type;
  const char *message;
  const char *key;
  bool enabled;
};

// Delivers a `KeyboardLockSnapshotC` (borrowed for the call only) to C++.
using KeyboardLockSnapshotFn = void(*)(void*, const KeyboardLockSnapshotC*);

// Zero-copy snapshot handed to the C++ side. The `*const c_char` fields borrow
// `CString`s that live on the worker stack **only for the duration of the
// callback**; C++ must copy them (`QString::fromUtf8`) synchronously and must
// not retain the pointers. Fields map 1:1 to `SysInfoProvider` QML properties.
struct SysInfoSnapshotC {
  double cpu;
  int32_t mem;
  const char *mem_used;
  const char *mem_total;
  int32_t disk;
  int32_t disk_worst_case;
  bool disk_btrfs_available;
  double disk_btrfs_free_est_gib;
  double disk_btrfs_free_min_gib;
  const char *disk_health;
  const char *disk_wear;
  const char *disk_device;
  double temp;
  const char *uptime;
  double psi_cpu_some;
  double psi_cpu_full;
  double psi_mem_some;
  double psi_mem_full;
  double psi_io_some;
  double psi_io_full;
  const char *error;
};

// Delivers a `SysInfoSnapshotC` (borrowed for the call only) to the C++ side.
using SysInfoSnapshotFn = void(*)(void*, const SysInfoSnapshotC*);

extern "C" {

// Installs the fatal-abort panic hook. Called once from the QML plugin's
// `registerTypes` so it is not coupled to any single provider's lifecycle.
void QsNative_InstallPanicHook();

// Starts an AI streaming session on a background thread.
//
// # Safety
//
// All pointer arguments must be either null or point to valid NUL-terminated
// strings for the duration of this call. `cb` must remain valid until the
// stream sends a terminal callback, and `ctx` must remain valid for each
// callback invocation.
//
// # Panics
//
// Panics if the internal session registry mutex is poisoned.
int QsNative_AiChat_Stream(const char *model_id,
                           const char *provider_config_json,
                           const char *system_prompt,
                           const char *conversation_id,
                           const char *message,
                           const char *attachments_json,
                           const char *disabled_tool_servers_json,
                           TokenCallback cb,
                           void *ctx);

// Requests cancellation of an in-flight streaming session by id.
//
// # Panics
//
// Panics if the internal session registry mutex is poisoned.
void QsNative_AiChat_Cancel(int id);

// Returns the JSON-encoded metrics for the most recently completed turn.
//
// # Panics
//
// Panics if the internal metrics mutex is poisoned.
char *QsNative_AiChat_LastMetrics();

char *QsNative_AiModels_Catalog(const char *provider_config_json,
                                const char *provider_order_json,
                                const char *configured_models_json);

BacklightHandle *QsNative_Backlight_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_Backlight_New` not yet freed.
// Dropping the handle drops the watcher, which stops the watch thread cleanly.
void QsNative_Backlight_Delete(BacklightHandle *handle);

// True when the `ddcutil` binary is on `PATH` and executable. Pure PATH scan;
// used to prime `ddcutil_available` during C++ construction (before `start()`).
bool QsNative_Backlight_DdcutilAvailable();

// Reads the internal backlight synchronously and delivers its state
// (`available`, `brightness_percent`, `device`, `error`) through `cb` as a
// borrowed `BacklightSnapshotC`. `cb` fires once, synchronously, before return.
//
// # Safety
// `ctx`/`cb` must be valid for the duration of the call.
void QsNative_Backlight_Refresh(void *ctx, BacklightSnapshotFn cb);

// Writes `percent` to the internal backlight, then delivers the resulting state
// (or the failure state on error) through `cb` as a borrowed `BacklightSnapshotC`.
// `cb` fires once, synchronously, before return.
//
// # Safety
// `ctx`/`cb` must be valid for the duration of the call.
void QsNative_Backlight_SetBrightness(int32_t percent, void *ctx, BacklightSnapshotFn cb);

// Installs (or reuses) a `notify` watcher on the sysfs `.../brightness` file.
// On Modify/Create the watcher reads fresh state and delivers it through `cb`
// as a borrowed `BacklightSnapshotC` (the C++ side copies it but must not retain
// the pointers). Returns an error string as owned `char*` ("" on success); freed
// with `QsNative_Free`.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must stay valid until the watcher is
// dropped (via `stopMonitor` or `Delete`).
char *QsNative_Backlight_StartMonitor(BacklightHandle *handle, void *ctx, BacklightSnapshotFn cb);

// Drops the sysfs watcher, stopping the watch thread.
//
// # Safety
// `handle` must be null or a valid handle.
void QsNative_Backlight_StopMonitor(BacklightHandle *handle);

// Re-checks `ddcutil` availability and returns it. When unavailable the DDC map
// is cleared synchronously (C++ then bumps the version). When available a worker
// thread runs `ddcutil detect`, stores the connector→bus map, and fires `cb` to
// bump the change-notification version.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid until `cb` fires.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
bool QsNative_Backlight_RefreshDdc(BacklightHandle *handle, void *ctx, QsNativeUpdateFn cb);

// I2C bus string for a connector ("" when unmapped). Freed with `QsNative_Free`.
//
// # Safety
// `handle` must be valid; `connector` a valid C string.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
char *QsNative_Backlight_DdcBusForConnector(BacklightHandle *handle, const char *connector);

// Current DDC brightness as a 0-100 percent (0 when missing/unknown).
//
// # Safety
// `handle` must be valid; `connector` a valid C string.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
int32_t QsNative_Backlight_DdcBrightnessPercent(BacklightHandle *handle, const char *connector);

// Max DDC brightness for a connector (100 fallback).
//
// # Safety
// `handle` must be valid; `connector` a valid C string.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
int32_t QsNative_Backlight_DdcMaxBrightness(BacklightHandle *handle, const char *connector);

// Last DDC error string for a connector ("" when ok). Freed with `QsNative_Free`.
//
// # Safety
// `handle` must be valid; `connector` a valid C string.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
char *QsNative_Backlight_DdcError(BacklightHandle *handle, const char *connector);

// Reads a single connector's DDC brightness off-thread and bumps the version.
// Returns false (no work started) when the connector is unmapped.
//
// # Safety
// `handle` must be valid; `connector` a valid C string; `ctx`/`cb` valid until
// `cb` fires.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
bool QsNative_Backlight_RefreshDdcBrightness(BacklightHandle *handle,
                                             const char *connector,
                                             void *ctx,
                                             QsNativeUpdateFn cb);

// Sets a connector's DDC brightness off-thread (setvcp then getvcp) and bumps
// the version. Returns false (no work started) when the connector is unmapped.
//
// # Safety
// `handle` must be valid; `connector` a valid C string; `ctx`/`cb` valid until
// `cb` fires.
//
// # Panics
// Panics if the shared DDC state mutex is poisoned by a prior panic.
bool QsNative_Backlight_SetDdcBrightness(BacklightHandle *handle,
                                         const char *connector,
                                         int32_t percent,
                                         void *ctx,
                                         QsNativeUpdateFn cb);

// # Safety
//
// `devices_json` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_BluetoothDevices(const char *devices_json);

// # Safety
//
// `text` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_ParseLibrepodsTooltip(const char *text);

// # Safety
//
// `players_json` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_ActiveMprisPlayer(const char *players_json);

// # Safety
//
// `player_json` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_SpotifyTrackRef(const char *player_json);

// # Safety
//
// Arguments must be null or point to valid NUL-terminated UTF-8 C strings.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_LyricsLookupKey(const char *track,
                                              const char *artist,
                                              const char *album,
                                              const char *length_micros);

// # Safety
//
// `error_text` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_IsNoLyricsError(const char *error_text);

// # Safety
//
// `source` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_LyricsSourceInfo(const char *source);

// # Safety
//
// `output` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_ParseSystemdIdleInhibitors(const char *output);

// # Safety
//
// `output` must be null or point to a valid NUL-terminated UTF-8 C string.
// The returned pointer must be released with `QsNative_Free`.
char *QsNative_BarModuleLogic_ParsePortalSessionCount(const char *output);

BluetoothHandle *QsNative_Bluetooth_New();

// # Panics
// Panics if the monitor mutex is poisoned (a worker thread panicked while holding it).
//
// # Safety
// `handle` must be null or a pointer from `QsNative_Bluetooth_New` not yet freed.
void QsNative_Bluetooth_Delete(BluetoothHandle *handle);

// Spawns the system-bus discovery monitor. Each resolved caller is delivered as
// a partial snapshot; when the monitor thread exits it delivers `monitoring =
// false` (plus `error` on failure). Re-entrancy is guarded on the C++ side via
// the `monitoring` property, so any previously-finished thread is joined and
// replaced here.
//
// # Panics
// Panics if the monitor mutex is poisoned (a worker thread panicked while holding it).
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid until the worker exits
// (the C++ side joins it in `_Delete`).
void QsNative_Bluetooth_StartDiscoveryMonitor(BluetoothHandle *handle,
                                              void *ctx,
                                              QsNativeUpdateFn cb);

// Signals the running discovery monitor to stop. The worker notices the flag,
// exits, and delivers `monitoring = false`.
//
// # Panics
// Panics if the monitor mutex is poisoned (a worker thread panicked while holding it).
//
// # Safety
// `handle` must be valid.
void QsNative_Bluetooth_StopDiscoveryMonitor(BluetoothHandle *handle);

// Scans procfs for processes matching `HOLDER_KEYWORDS`, returning the
// newline-joined table. Runs synchronously on the caller (Qt) thread. The
// returned pointer must be released with `QsNative_Free`.
char *QsNative_Bluetooth_ScanHolders();

// Spawns a session-bus probe for the librepods `StatusNotifierItem` tooltip.
// Delivers `librepods_tooltip` + `error` (error cleared on success).
//
// # Safety
// `ctx`/`cb` must remain valid until the worker fires.
void QsNative_Bluetooth_ProbeLibrepodsTooltip(void *ctx, QsNativeUpdateFn cb);

// Restores the latest active conversation for a model.
//
// # Safety
//
// Pointer arguments must be null or valid NUL-terminated strings for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_Restore(const char *model_id,
                                 const char *provider_id,
                                 const char *system_prompt);

// Creates a fresh active conversation.
//
// # Safety
//
// Pointer arguments must be null or valid NUL-terminated strings for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_Create(const char *model_id,
                                const char *provider_id,
                                const char *system_prompt);

// Closes an active conversation.
//
// # Safety
//
// `conversation_id` must be null or a valid NUL-terminated string for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_Close(const char *conversation_id);

// Resumes a closed conversation and returns its messages.
//
// # Safety
//
// Pointer arguments must be null or valid NUL-terminated strings for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_Resume(const char *model_id,
                                const char *provider_id,
                                const char *system_prompt,
                                const char *current_conversation_id,
                                const char *target_conversation_id);

// Lists closed conversations available for resume.
//
// # Safety
//
// Pointer arguments must be null or valid NUL-terminated strings for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_ListResume(const char *model_id,
                                    const char *provider_id,
                                    const char *current_conversation_id,
                                    const char *query,
                                    int32_t limit);

// Inserts or updates a message row from a compact JSON object.
//
// # Safety
//
// `message_json` must be null or a valid NUL-terminated string for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_UpsertMessage(const char *message_json);

// Deletes one message row and compacts later ordinals.
//
// # Safety
//
// `message_id` must be null or a valid NUL-terminated string for the duration
// of this call. The returned pointer must be released with `QsNative_Free`.
char *QsNative_AiHistory_MarkMessageDeleted(const char *message_id);

// Deletes all rows from an ordinal onward.
//
// # Safety
//
// `conversation_id` must be null or a valid NUL-terminated string for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_DeleteFromOrdinal(const char *conversation_id, int32_t ordinal);

// Inserts or updates a tool-call row from a compact JSON object.
//
// # Safety
//
// `tool_call_json` must be null or a valid NUL-terminated string for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_UpsertToolCall(const char *tool_call_json);

// Inserts or updates response-item rows from a compact JSON array.
//
// # Safety
//
// Pointer arguments must be null or valid NUL-terminated strings for the
// duration of this call. The returned pointer must be released with
// `QsNative_Free`.
char *QsNative_AiHistory_UpsertResponseItems(const char *conversation_id,
                                             const char *turn_id,
                                             int32_t turn_ordinal,
                                             const char *response_items_json);

ConfigResolverHandle *QsNative_ConfigResolver_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_ConfigResolver_New` not yet freed.
void QsNative_ConfigResolver_Delete(ConfigResolverHandle *handle);

// Resolves the current config/secret values as a JSON object (string -> string).
//
// TODO(stage2): reload `config.toml` and overlay Secret Service keys. For now
// this returns an empty object; the returned pointer must be freed with
// `QsNative_Free`.
//
// # Safety
// `handle` must be valid; the returned pointer must be released with `QsNative_Free`.
char *QsNative_ConfigResolver_Refresh(ConfigResolverHandle *handle);

// Fetches the configured Google Calendars on a background thread and delivers
// the full JSON payload (`{generatedAt, status, error?, eventsByDay}`) to C++
// via `cb`. The C++ `QsNativeIcal` copies the borrowed string, marshals it onto
// the Qt thread, and parses `generatedAt`/`status`/`error` out of it before
// applying `events_json` as the change trigger.
//
// # Safety
// `ctx`/`cb` must remain valid until `cb` fires.
void QsNative_Ical_Refresh(void *ctx, QsNativeUpdateFn cb, int32_t days);

IdleHandle *QsNative_Idle_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_Idle_New` not yet freed.
void QsNative_Idle_Delete(IdleHandle *handle);

// Delivers the current property snapshot as a zero-copy `IdleSnapshotC` via
// `cb`. Synchronous: `cb` fires on the caller's thread before this returns.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid until `cb` fires.
void QsNative_Idle_Snapshot(IdleHandle *handle, void *ctx, IdleSnapshotFn cb);

// Loads settings from `path`; on failure applies defaults and records an error.
//
// # Safety
// `handle` must be valid; `path` must be null or a valid C string.
bool QsNative_Idle_LoadSettings(IdleHandle *handle, const char *path);

// Clamps then applies the given settings and writes them atomically to `path`.
//
// # Safety
// `handle` must be valid; `path` must be null or a valid C string.
bool QsNative_Idle_SaveSettings(IdleHandle *handle,
                                const char *path,
                                int32_t display_off_timeout_sec,
                                int32_t suspend_timeout_sec,
                                bool suspend_enabled,
                                bool ignore_lid_events);

// Pure `max(0)` clamp of a timeout value; no handle state involved.
int32_t QsNative_Idle_ClampTimeout(int32_t seconds);

// Builds the `idle` IPC status payload as an owned JSON `char*`
// (release with `QsNative_Free`).
//
// # Safety
// `handle` must be valid.
char *QsNative_Idle_StatusJson(IdleHandle *handle,
                               bool dpms_off,
                               double next_suspend_at_ms,
                               bool sleep_inhibited,
                               double now_ms);

// Spawns or kills the `systemd-inhibit` lid-switch blocker and updates the
// `lidInhibited`/`error` state.
//
// # Safety
// `handle` must be valid.
bool QsNative_Idle_SyncLidInhibitProcess(IdleHandle *handle, bool inhibited);

KeyboardLockHandle *QsNative_KeyboardLock_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_KeyboardLock_New` not yet
// freed. Any in-flight worker callback is drained before the handle drops.
//
// # Panics
// Panics if the gate mutex is poisoned (a worker thread panicked while holding it).
void QsNative_KeyboardLock_Delete(KeyboardLockHandle *handle);

// Spawns the evdev reader thread. `ctx`/`cb` deliver events back to the
// `QObject`; the caller is responsible for the empty-path case (it never calls
// here with an empty path).
//
// # Safety
// `handle` must be valid; `path` a valid C string; `ctx`/`cb` must stay valid
// until `QsNative_KeyboardLock_Delete` drains the gate.
//
// # Panics
// Panics if the gate mutex is poisoned (a worker thread panicked while holding it).
void QsNative_KeyboardLock_Start(KeyboardLockHandle *handle,
                                 const char *path,
                                 void *ctx,
                                 KeyboardLockSnapshotFn cb);

// # Safety
// `handle` must be null or a valid handle pointer.
void QsNative_KeyboardLock_Stop(KeyboardLockHandle *handle);

char *QsNative_AiMcp_Refresh();

// Frees a string returned by a `QsNative_*` C ABI function.
//
// # Safety
//
// `s` must be null or a pointer previously returned by this Rust library via
// `CString::into_raw`. Passing any other pointer is undefined behavior.
void QsNative_Free(char *s);

NetStatsHandle *QsNative_NetStats_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_NetStats_New` not yet freed.
void QsNative_NetStats_Delete(NetStatsHandle *handle);

// Reads `/proc/net/dev` for `device` (borrowed C string). Returns an owned JSON
// object string `{ok, error, rx_bytes?, tx_bytes?}`; `rx_bytes`/`tx_bytes` are
// only present when `ok` is true. Stateless: does not touch the handle.
//
// # Safety
// `device` must be null or a valid NUL-terminated string for the call.
char *QsNative_NetStats_Refresh(const char *device);

// Folds a fresh cumulative sample into the EMA rates + history, returning the
// traffic snapshot (rates, scale, history JSON).
//
// # Safety
// `handle` must be a valid pointer from `QsNative_NetStats_New`.
char *QsNative_NetStats_UpdateTrafficRates(NetStatsHandle *handle,
                                           double rx_bytes,
                                           double tx_bytes,
                                           double now_ms);

// Clears the traffic history and zeroes the rates, returning the reset snapshot.
//
// # Safety
// `handle` must be a valid pointer from `QsNative_NetStats_New`.
char *QsNative_NetStats_ResetTraffic(NetStatsHandle *handle);

// Normalizes + sorts the source entries JSON. On success rewrites the stored
// entries and auto-clears the switch state if the switching source is now
// active. Returns `{ok, error, <source snapshot>}`.
//
// # Safety
// `handle` valid; `entries_json` null or valid NUL-terminated string.
char *QsNative_NetStats_SetSourceEntries(NetStatsHandle *handle, const char *entries_json);

// Marks a source switch as in flight. Returns `{ok, <source snapshot>}`; `ok`
// is false if `name` is blank or a switch is already running.
//
// # Safety
// `handle` valid; `name` null or valid NUL-terminated string.
char *QsNative_NetStats_BeginSourceSwitch(NetStatsHandle *handle, const char *name);

// Records a switch failure message and clears the in-flight state. Returns the
// source snapshot.
//
// # Safety
// `handle` valid; `message` null or valid NUL-terminated string.
char *QsNative_NetStats_FailSourceSwitch(NetStatsHandle *handle, const char *message);

// Clears the switch flag, name, and error. Returns the source snapshot.
//
// # Safety
// `handle` must be a valid pointer from `QsNative_NetStats_New`.
char *QsNative_NetStats_ClearSourceSwitch(NetStatsHandle *handle);

// Parses `ip -j -4 addr show` JSON; returns the first `local/prefixlen` (or
// `local`) inet address, or an empty string.
//
// # Safety
// `text` must be null or a valid NUL-terminated string for the call.
char *QsNative_NetStats_ParseIpAddressJson(const char *text);

// Parses `ip -j route show default` JSON; returns the first non-empty gateway,
// or an empty string.
//
// # Safety
// `text` must be null or a valid NUL-terminated string for the call.
char *QsNative_NetStats_ParseGatewayJson(const char *text);

// Trims and replaces `_` with spaces in a udev-derived label.
//
// # Safety
// `text` must be null or a valid NUL-terminated string for the call.
char *QsNative_NetStats_NormalizeEthernetLabel(const char *text);

// Resolves ethernet/USB NIC metadata via sysfs + `udevadm`, returning a JSON
// object string `{subsystem,label}` (`{}` on failure). Shells out synchronously.
//
// # Safety
// `device_name` must be null or a valid NUL-terminated string for the call.
char *QsNative_NetStats_EthernetMetadataJson(const char *device_name);

PacmanHandle *QsNative_Pacman_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_Pacman_New` not yet freed.
void QsNative_Pacman_Delete(PacmanHandle *handle);

// Kicks off a background refresh and delivers a JSON snapshot via `cb`.
//
// TODO(stage2): run `checkupdates` + `yay -Qua` here. The stub delivers an
// empty snapshot so the QML "refresh completed" signals still fire.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid until `cb` fires.
void QsNative_Pacman_Refresh(PacmanHandle *handle, bool _no_aur, void *ctx, QsNativeUpdateFn cb);

// Kicks off a detached database sync.
//
// TODO(stage2): spawn `sudo -n pacman -Sy --noconfirm`. The stub is a no-op.
//
// # Safety
// `handle` must be valid.
void QsNative_Pacman_Sync(PacmanHandle *handle);

PrivacyHandle *QsNative_Privacy_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_Privacy_New` not yet freed.
void QsNative_Privacy_Delete(PrivacyHandle *handle);

// Spawns the persistent inotify camera watcher. Delivers `camera_event` and
// `monitor_exited` JSON events via `cb`.
//
// # Safety
// `handle`/`device` must be valid; `ctx`/`cb` must stay valid for the `QObject`
// lifetime (guarded by the handle's alive flag).
void QsNative_Privacy_StartWatch(PrivacyHandle *handle,
                                 void *ctx,
                                 QsNativeUpdateFn cb,
                                 const char *device);

// Probes camera holders on a worker thread and delivers a `probe` JSON event.
// `from_open` selects the retry policy (used for OPEN events / explicit
// refreshes) and is echoed back so the C++ side can derive the retry counter.
//
// # Safety
// `handle`/`device` must be valid; `ctx`/`cb` must stay valid until `cb` fires.
void QsNative_Privacy_Probe(PrivacyHandle *handle,
                            void *ctx,
                            QsNativeUpdateFn cb,
                            const char *device,
                            bool from_open,
                            bool debug);

// Classifies a JSON array of `PipeWire` nodes. Returns an owned JSON object:
// `{"ok":true,"microphone_active":bool,"screensharing_active":bool}` on success
// or `{"ok":false,"error":"..."}` on parse failure. Free with `QsNative_Free`.
//
// # Safety
// `json` must be null or a valid NUL-terminated string.
char *QsNative_Privacy_ClassifyPipewire(const char *json);

SysInfoHandle *QsNative_SysInfo_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_SysInfo_New` not yet freed.
void QsNative_SysInfo_Delete(SysInfoHandle *handle);

// Reads system metrics on a background thread and delivers a `SysInfoSnapshotC`
// via `cb`. State (previous CPU sample, throttled disk/btrfs caches) lives in
// the handle behind a mutex, so overlapping refreshes serialize safely.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid until `cb` fires.
//
// # Panics
// The worker thread panics if the shared state mutex has been poisoned by a
// prior panic while holding the lock.
void QsNative_SysInfo_Refresh(SysInfoHandle *handle, void *ctx, SysInfoSnapshotFn cb);

SystemdFailedHandle *QsNative_SystemdFailedProvider_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_SystemdFailedProvider_New`
// that has not yet been freed.
void QsNative_SystemdFailedProvider_Delete(SystemdFailedHandle *handle);

// Delivers a failed-unit snapshot to C++ via `cb`.
//
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid until `cb` returns.
void QsNative_SystemdFailedProvider_Refresh(SystemdFailedHandle *handle,
                                            void *ctx,
                                            QsNativeUpdateFn cb);

TodoistHandle *QsNative_Todoist_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_Todoist_New` not yet freed.
void QsNative_Todoist_Delete(TodoistHandle *handle);

// Runs a blocking Todoist sync on a worker thread and delivers a JSON snapshot
// (`{data, error, last_updated}`) via `cb`. `data` is itself the serialized
// `ListOutput` JSON string.
//
// # Safety
// `cache_path` must be null or valid for the call; `ctx`/`cb` must remain valid
// until `cb` fires.
void QsNative_Todoist_Refresh(TodoistHandle *_handle,
                              const char *cache_path,
                              bool prefer_cache,
                              void *ctx,
                              QsNativeUpdateFn cb);

// Applies a mutating Todoist command (close/delete/add/update), then re-syncs
// and delivers the refreshed snapshot via `cb`. On failure it logs and falls
// back to a cache-preferring refresh carrying the error message.
//
// # Safety
// `verb`/`args_json`/`cache_path` must be null or valid for the call;
// `ctx`/`cb` must remain valid until `cb` fires.
void QsNative_Todoist_Action(TodoistHandle *_handle,
                             const char *verb,
                             const char *args_json,
                             const char *cache_path,
                             void *ctx,
                             QsNativeUpdateFn cb);

}  // extern "C"
