#pragma once

// Auto-generated by cbindgen from the Rust extern "C" surface. Do not edit; edit the Rust and rebuild.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Opaque per-instance handle owned by the C++ `QsNativeMaterialPopup` `QObject`.
struct MaterialPopupHandle;

// Callback used to deliver a JSON event to C++. The `json` pointer is borrowed
// for the duration of the call only: C++ copies it (`QString::fromUtf8`) and
// must **not** free it.
using MaterialPopupUpdateFn = void(*)(void *ctx, const char *json);

extern "C" {

// Creates a handle that delivers events to `cb`/`ctx`. The caller must keep
// `ctx`/`cb` valid until `QsNative_MaterialPopup_Delete`.
MaterialPopupHandle *QsNative_MaterialPopup_New(void *ctx, MaterialPopupUpdateFn cb);

// # Safety
// `handle` must be null or a pointer from `QsNative_MaterialPopup_New` not yet
// freed.
//
// # Panics
// Panics if the shared-state mutex has been poisoned by a panic in a worker
// thread.
void QsNative_MaterialPopup_Delete(MaterialPopupHandle *handle);

// Spawns the clipboard watcher and input monitor if not already running.
//
// # Safety
// `handle` must be valid.
//
// # Panics
// Panics if the shared-state mutex has been poisoned by a panic in a worker
// thread.
void QsNative_MaterialPopup_Start(MaterialPopupHandle *handle);

// Signals the worker threads to stop and clears the running flag.
//
// # Safety
// `handle` must be valid.
//
// # Panics
// Panics if the shared-state mutex has been poisoned by a panic in a worker
// thread.
void QsNative_MaterialPopup_Stop(MaterialPopupHandle *handle);

}  // extern "C"
