color0 #11140f
color1 #ffb4ab
color2 #a8d292
color3 #bccbb0
color4 #a0cfd0
color5 #a8d292
color6 #bccbb0
color7 #e1e4da
color8 #8d9287
color9 #ffb4ab
color10 #a8d292
color11 #bccbb0
color12 #a0cfd0
color13 #a8d292
color14 #bccbb0
color15 #e1e4da

cursor                #e1e4da
cursor_text_color     #11140f
background            #10180b
foreground            #e1e4da
selection_foreground  #c3c8bb
selection_background  #43483f
active_border_color   #a8d292
inactive_border_color #43483f
url_color             #a8d292


# Tab bar colors
active_tab_foreground   #153808
active_tab_background   #a8d292
inactive_tab_foreground #c3c8bb
inactive_tab_background #0c0f0a
tab_bar_background      #272b25
