#pragma once

// Auto-generated by cbindgen from the Rust extern "C" surface. Do not edit; edit the Rust and rebuild.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Opaque per-instance handle owned by the C++ `QsNativeMarkdownStream` `QObject`.
struct MarkdownStreamHandle;

// A single resolved markdown row, borrowed for the duration of the callback.
struct MarkdownRowC {
  uint64_t block_id;
  const char *kind;
  const char *block_type;
  const char *content;
  const char *raw;
  const char *display;
  bool completed;
  const char *language;
};

// Delivers the current full row snapshot (borrowed for the call only) to the
// C++ side. Called synchronously, on the caller's thread.
using MarkdownRowsFn = void(*)(void*, const MarkdownRowC*, uintptr_t);

extern "C" {

MarkdownStreamHandle *QsNative_MarkdownStream_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_MarkdownStream_New` not yet freed.
void QsNative_MarkdownStream_Delete(MarkdownStreamHandle *handle);

// Feeds the full content text (delta-appended when it extends the previous
// content, otherwise a hard reset) and delivers the resulting row snapshot
// via `cb`, called synchronously before this function returns.
//
// # Safety
// `handle` must be valid; `content` must be null or a valid C string;
// `ctx`/`cb` must remain valid for the duration of this call.
void QsNative_MarkdownStream_SetContent(MarkdownStreamHandle *handle,
                                        const char *content,
                                        void *ctx,
                                        MarkdownRowsFn cb);

// Sets streaming mode (finalizing the pending block when turned off) and
// delivers the resulting row snapshot via `cb`, called synchronously before
// this function returns.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid for the duration of
// this call.
void QsNative_MarkdownStream_SetStreaming(MarkdownStreamHandle *handle,
                                          bool streaming,
                                          void *ctx,
                                          MarkdownRowsFn cb);

// Commits the pending block and delivers the resulting row snapshot via
// `cb`, called synchronously before this function returns.
//
// # Safety
// `handle` must be valid; `ctx`/`cb` must remain valid for the duration of
// this call.
void QsNative_MarkdownStream_Finalize(MarkdownStreamHandle *handle, void *ctx, MarkdownRowsFn cb);

}  // extern "C"
