#pragma once

// Auto-generated by cbindgen from the Rust extern "C" surface. Do not edit; edit the Rust and rebuild.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Opaque per-instance handle owned by the C++ `QsNativeMarkdownStream` `QObject`.
//
// TODO(stage2): hold the real `MdStream` / `DocumentState` and the parsed rows.
struct MarkdownStreamHandle;

extern "C" {

MarkdownStreamHandle *QsNative_MarkdownStream_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_MarkdownStream_New` not yet freed.
void QsNative_MarkdownStream_Delete(MarkdownStreamHandle *handle);

// Feeds the full content text and returns the resulting block count.
//
// TODO(stage2): re-parse (delta append or reset) and return the real count.
//
// # Safety
// `handle` must be valid; `content` must be null or a valid C string.
int32_t QsNative_MarkdownStream_SetContent(MarkdownStreamHandle *handle, const char *content);

// Sets streaming mode and returns the resulting block count.
//
// TODO(stage2): finalize the pending block when `streaming` becomes false.
//
// # Safety
// `handle` must be valid.
int32_t QsNative_MarkdownStream_SetStreaming(MarkdownStreamHandle *handle, bool streaming);

// Commits the pending block and returns the resulting block count.
//
// TODO(stage2): call `stream.finalize()` + refresh.
//
// # Safety
// `handle` must be valid.
int32_t QsNative_MarkdownStream_Finalize(MarkdownStreamHandle *handle);

}  // extern "C"
