#pragma once

// Auto-generated by cbindgen from the Rust extern "C" surface. Do not edit; edit the Rust and rebuild.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Opaque per-instance handle owned by the C++ `QsNativeUnifiedLyrics` `QObject`.
struct UnifiedLyricsHandle;

extern "C" {

UnifiedLyricsHandle *QsNative_UnifiedLyrics_New();

// # Safety
// `handle` must be null or a pointer from `QsNative_UnifiedLyrics_New` not yet freed.
void QsNative_UnifiedLyrics_Delete(UnifiedLyricsHandle *handle);

// STUB refresh: validates that a track and artist are present but performs no
// network fetch. Returns `false` when `track_name` or `artist_name` is empty
// after trim, `true` otherwise. No properties change.
//
// # Safety
// `handle` must be valid; the string args must be null or valid NUL-terminated
// strings for the duration of the call.
bool QsNative_UnifiedLyrics_Refresh(UnifiedLyricsHandle *handle,
                                    const char *spotify_track_ref,
                                    const char *track_name,
                                    const char *artist_name,
                                    const char *album_name,
                                    const char *length_micros);

}  // extern "C"
