$border               = rgb(ffb3b1)
$red                  = rgb(ffb4ab)
$surface1             = rgb(322827)
$base                 = rgb(1a1111)

$text_hex             = f0dedd
$subtext_hex          = d7c1c0

$text                 = rgb($text_hex)
$subtext              = rgb($subtext_hex)
$overlay1             = rgb(a08c8b)
$overlay2             = rgb(524342)

$blue_glow            = rgba(ffb3b1)
