$border               = rgb(c0c1ff)
$red                  = rgb(ffb4ab)
$surface1             = rgb(2a292f)
$base                 = rgb(131318)

$text_hex             = e4e1e9
$subtext_hex          = c7c5d0

$text                 = rgb($text_hex)
$subtext              = rgb($subtext_hex)
$overlay1             = rgb(918f9a)
$overlay2             = rgb(46464f)

$blue_glow            = rgba(c0c1ff)
