$border               = rgb(ffb4a8)
$red                  = rgb(ffb4ab)
$surface1             = rgb(322826)
$base                 = rgb(1a1110)

$text_hex             = f1dfdc
$subtext_hex          = d8c2be

$text                 = rgb($text_hex)
$subtext              = rgb($subtext_hex)
$overlay1             = rgb(a08c89)
$overlay2             = rgb(534341)

$blue_glow            = rgba(ffb4a8)
