arch = [
	"uwsm",
	"hyprland",
	"hyprgrass-meta",	# Hyprgrass dependency
	"adwaita-qt5",
	"adwaita-qt6",
	"rose-pine-hyprcursor",
	"rofi-wayland",
	"rofi-calc-git",
	"waybar",
	"xdg-desktop-portal-hyprland",
	"xdg-desktop-portal-gtk",
	"gnome-keyring",
	"wev",	# for debugging purposes
	
	"swww",
	"eww",
	"dunst",
	"hypridle",
	"hyprlock",
	"hyprshot",
	"zbar",
	"tesseract",
	"tesseract-data-eng",
	"ripdrag-git",
	"hyprsunset",
	"hyprpolkitagent",

	"btrfs-assistant",

	"spicetify-cli",
	"spotify",
	"brave-bin",
	"localsend",
	"nautilus",
	"kitty",
	"neovide",
	"clapper",	# video player
	"visual-studio-code-bin",
	"qbittorrent",
	"ventoy-bin",
	"universal-android-debloater-bin",

	"ttf-jetbrains-mono-nerd",
	"noto-fonts-jp-vf",
]
