# Window and layer rules
# Make special workspaces more recognisable
windowrule {
  name = windowrule-1
  border_size = 2
  border_color = $red
  match:workspace = s[1]
}


windowrule {
  name = windowrule-2
  float = on
  match:class = ^(hyprland-share-picker)$
}


windowrule {
  name = sushi_preview
  float = on
  match:class = ^(org.gnome.NautilusPreviewer)$
}


windowrule {
  name = pin_ripdrag
  pin = on
  match:class = ^(it.catboy.ripdrag)$
}


layerrule {
  name = vicinae
  dim_around = on
  blur = on
  ignore_alpha = 0
  xray = 0
  match:namespace = vicinae
}


windowrule {
  name = set_waybar_controls
  tag = +waybar-control
  match:class = (impala|bluetui)
}

# https://www.reddit.com/r/hyprland/comments/1eu3qdv/screenshot_captures_selection_outline_with_grim/
layerrule {
  name = selection
  no_anim = on
  match:namespace = selection
}


layerrule {
  name = powermenu
  blur = on
  dim_around = on
  match:namespace = powermenu
}


windowrule {
  name = whatsapp_silent
  workspace = special:whatsapp silent
  match:initial_title = ^(web.whatsapp.com_/)$
}

windowrule {
  name = spotify
  workspace = special:spotify
  match:initial_class = ^(spotify)$
}


# chromium preview windows
windowrule {
  name = assign_popup
  tag = +popup
  match:class = ^()$
  match:title = ^()$
}

windowrule {
  # automagically popup window to whichever direction is needed. use the regular popup
  # for less magic (ie bottom right as much as is viable without jutting outta screen)
  name = magic_popups
  move = min(max(0,(cursor_x>monitor_w*0.5)?(cursor_x-window_w):cursor_x),monitor_w-window_w) min(max(0,(cursor_y>monitor_h*0.5)?(cursor_y-window_h):cursor_y),monitor_h-window_h)
  float = on
  match:tag = popup
}

# windowrule {
#   # automagically popup window to whichever direction is needed. use the regular popup
#   # for less magic (ie bottom right as much as is viable without jutting outta screen)
#   name = popups
#   move = min(cursor_x,(monitor_w-window_w)) min(cursor_y,monitor_h-window_h)
#   float = on
#   match:tag = popup
# }
