typeset -g POWERLEVEL9K_BACKGROUND={{colors.surface_variant.default.hex}} 
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND={{colors.primary.default.hex}}
typeset -g POWERLEVEL9K_TIME_FOREGROUND={{colors.on_surface_variant.default.hex}}
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND={{colors.tertiary.default.hex}}
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND={{colors.tertiary.default.hex}}
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND={{colors.tertiary.default.hex}}
